services:
  - type: web
    name: rewear-app
    env: python
    plan: free  # You can upgrade to a paid plan later
    buildCommand: "./build.sh"
    startCommand: "gunicorn --config gunicorn_config.py app:app"
    envVars:
      - key: DEBUG
        value: "false"
      - key: SECRET_KEY
        generateValue: true  # Render will generate a secure secret key
      - key: DB_ENGINE
        value: "postgresql"
      - key: PYTHON_VERSION
        value: "3.11.0"

  - type: pserv
    name: rewear-database
    env: docker
    plan: free  # Free PostgreSQL database
    disk:
      name: postgres-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1

# Optional: For static files (if you have any)
# - type: static
#   name: rewear-static
#   buildCommand: "echo 'No build needed for static files'"
#   staticPublishPath: ./static
