"""Add moderation fields to Item model

Revision ID: 08ab4ca06935
Revises: df9562491139
Create Date: 2025-07-12 14:16:48.549261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ab4ca06935'
down_revision = 'df9562491139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moderation_status', sa.String(length=20), nullable=False, server_default='pending'))
        batch_op.add_column(sa.Column('moderation_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('moderated_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('moderated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_items_moderated_by', 'users', ['moderated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_items_moderated_by', type_='foreignkey')
        batch_op.drop_column('moderated_at')
        batch_op.drop_column('moderated_by')
        batch_op.drop_column('moderation_notes')
        batch_op.drop_column('moderation_status')

    # ### end Alembic commands ###
