"""Add Item model with media support

Revision ID: 4b3da0e656d7
Revises: 
Create Date: 2025-07-12 13:42:36.524620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b3da0e656d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_filename', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=10), nullable=True))
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_filename')

    # ### end Alembic commands ###
